routes/web.php
<?php

use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\RoleSetupController;
use App\Http\Controllers\Admin\SurveyController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\UserSetupController;
use GuzzleHttp\Middleware;
use Illuminate\Http\Request;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::middleware(['auth'])->group(function () {
    Route::get('home', function () {
        return view('dashboard.home');
    })->name('home');

    Route::prefix('admin')->group(function () {
        Route::resource('user', UserController::class);
        Route::get('user/setup/{id}', [UserSetupController::class, 'index'])->name('user.setup');
        Route::post('user/setup', [UserSetupController::class, 'store'])->name('user.setup.store');
        Route::resource('permission', PermissionController::class);
        Route::resource('role', RoleController::class)->except(['show']);
        Route::get('role/setup/{id}', [RoleSetupController::class, 'index'])->name('role.setup');
        Route::post('role/setup', [RoleSetupController::class, 'store'])->name('role.setup.store');
        Route::resource('department', DepartmentController::class);
        Route::get('user/setup/department/{id}', [UserSetupController::class, 'indexDepartment'])->name('user.setup.department');
        Route::post('user/setup/department', [UserSetupController::class, 'storeDepartment'])->name('user.setup.department.store');
    });
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    public function __construct()
    {
        if ( ! auth()->user()->can('Read Role')) {
            abort(403);
        }
    }

    public function index()
    {
        $roles = Role::orderBy('name')->get();
        return view('admin.role.index', compact('roles'));
    }

    public function create()
    {
        return view('admin.role.create');
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
        ]);

        Role::create(['name' => $request->name]);

        return redirect('admin/role')->with('pesan', 'Data has been saved !');
    }

    public function edit($id)
    {
        $role = Role::find($id);

        return view('admin.role.edit', compact('role'));
    }

    public function update($id, Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
        ]);

        Role::whereId($id)->update(['name' => $request->name]);

        return redirect('admin/role')->with('pesan', 'Data has been changed !');
    }

    public function destroy($id)
    {
        Role::destroy($id);

        return redirect('admin/role')->with('pesan', 'Data has been deleted !');
    }
}

resources/views/admin/role/create.blade.php
@extends('layouts.app')

@section('title', 'Create Role')

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>Role - Create role</h1>
        </div>

        <div class="section-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route('role.store') }}" method="POST">
                                {{ csrf_field() }}
                                <div class="row">
                                    <div class="col">
                                        <input type="text" class="form-control" name="name" id="name" autofocus>
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="btn btn-success">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
@stop

resources/views/admin/role/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Role')

@section('content_header')
    <h1>Role</h1>
@stop

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>Role - Edit role</h1>
        </div>

        <div class="section-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route('role.update', $role->id) }}" method="POST">
                                @csrf
                                @method('PATCH')
                                <div class="row">
                                    <div class="col">
                                        <input type="text" class="form-control" name="name" id="name"
                                            value="{{ $role->name }}" autofocus>
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="btn btn-success">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
@stop

@section('css')

@stop

@section('js')

@stop

resources/views/admin/role/index.blade.php
@extends('layouts.app')

@section('title', 'Role')

@section('content')

    @if (session()->has('pesan'))
        <div class="alert alert-success alert-dismissible show fade">
            <div class="alert-body">
                <button class="close" data-dismiss="alert">
                    <span>×</span>
                </button>
                {{ session()->get('pesan') }}
            </div>
        </div>
    @endif

    <section class="section">
        <div class="section-header">
            <h1>Management users - role</h1>
        </div>

        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{ route('role.create') }}" class="btn btn-icon icon-left btn-primary"><i
                                    class="fas fa-plus"></i> Create</a>
                        </div>
                        <div class="card-body p-0">
                            <table class="table table-hover table-md     ml-4">
                                <tr>
                                    <th width="5%">No</th>
                                    <th>Nama</th>
                                    <th>Role</th>
                                    <th>Aksi</th>
                                </tr>

                                @php
                                    $no = 1;
                                @endphp
                                @foreach ($roles as $role)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $role->name }}</td>
                                        <td>
                                            @foreach ($role->getAllPermissions() as $item)
                                                {{ $item->name }} <br>
                                            @endforeach
                                        </td>
                                        <td>
                                            <a href="{{ route('role.edit', $role->id) }}"
                                                class="btn btn-warning btn-sm"><i class="fas fa-edit"></i></a>
                                            <form action="{{ route('role.destroy', $role->id) }}"
                                                method="POST" style="display: contents">
                                                @csrf
                                                @method('DELETE')

                                                <button type="submit" class="btn btn-danger btn-sm"
                                                    onclick="return hapus()"><i class="fas fa-trash"></i></button>
                                            </form>
                                            <a href="{{ route('role.setup', $role->id) }}" class="btn btn-primary btn-sm"
                                                data-toggle="tooltip" data-placement="top" title="Setup user"><i
                                                    class="fas fa-user-cog"></i></a>

                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
@stop

@push('js')

    <script>
        function hapus() {
            if (confirm('Are you sure you want to delete this data? Data that has been deleted cannot be recovered !!!')) {
                return true;
            } else {
                return false;
            }
        }
    </script>
@endpush

resources/views/admin/role/setup.blade.php
@extends('layouts.app')

@section('title', 'Setup permission role')

@section('content_header')
    <h1>Setup permission role</h1>
@stop

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>Role - Setup role</h1>
        </div>

        <div class="section-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route('role.setup.store') }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="id" value="{{ $role->id }}">
                                @foreach ($arPermissions as $group => $list)
                                    <h4>{{ $group }}</h3>
                                        @foreach ($list as $permission)
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" type="checkbox" name="permission[]"
                                                    value="{{ $permission }}"
                                                    @if ($role->hasPermissionTo($permission)) checked @endif>
                                                <label class="form-check-label">
                                                    {{ $permission }}
                                                </label>
                                            </div>
                                        @endforeach
                                        <br><br>
                                @endforeach
                                <button class="btn btn-success" type="submit">Save</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
@stop