routes/web.php
<?php

use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\RoleSetupController;
use App\Http\Controllers\Admin\SurveyController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\UserSetupController;
use GuzzleHttp\Middleware;
use Illuminate\Http\Request;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::middleware(['auth'])->group(function () {
    Route::get('home', function () {
        return view('dashboard.home');
    })->name('home');

    Route::prefix('admin')->group(function () {
        Route::resource('user', UserController::class);
        Route::get('user/setup/{id}', [UserSetupController::class, 'index'])->name('user.setup');
        Route::post('user/setup', [UserSetupController::class, 'store'])->name('user.setup.store');
        Route::resource('permission', PermissionController::class);
        Route::resource('role', RoleController::class)->except(['show']);
        Route::get('role/setup/{id}', [RoleSetupController::class, 'index'])->name('role.setup');
        Route::post('role/setup', [RoleSetupController::class, 'store'])->name('role.setup.store');
        Route::resource('department', DepartmentController::class);
        Route::get('user/setup/department/{id}', [UserSetupController::class, 'indexDepartment'])->name('user.setup.department');
        Route::post('user/setup/department', [UserSetupController::class, 'storeDepartment'])->name('user.setup.department.store');
    });
});

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    public function index()
    {
        $permissions = Permission::orderBy('name')->get();
        return view('admin.permission.index', compact('permissions'));
    }

    public function create()
    {
        return view('admin.permission.create');
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
        ]);

        Permission::create(['name' => $request->name]);

        return redirect('admin/permission')->with('pesan', 'Data has been saved !');
    }

    public function edit($id)
    {
        $permission = Permission::find($id);

        return view('admin.permission.edit', compact('permission'));
    }

    public function update($id, Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
        ]);

        Permission::whereId($id)->update(['name' => $request->name]);

        return redirect('admin/permission')->with('pesan', 'Data has been changed !');
    }

    public function destroy($id)
    {
        Permission::destroy($id);

        return redirect('admin/permission')->with('pesan', 'Data has been deleted !');
    }
}

resources/views/admin/permission/create.blade.php
@extends('layouts.app')

@section('title', 'Create Permission')

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>Permission - Create permission</h1>
        </div>

        <div class="section-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        {{-- <div class="card-header">

                        </div> --}}
                        <div class="card-body">
                            <form action="{{ route('permission.store') }}" method="POST">
                                {{ csrf_field() }}
                                <div class="row">
                                    <div class="col">
                                        <input type="text" class="form-control" name="name" id="name" autofocus>
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="btn btn-success">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>

@stop

resources/views/admin/permission/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Permission')

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>Permission - Edit permission</h1>
        </div>

        <div class="section-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        {{-- <div class="card-header">

                    </div> --}}
                        <div class="card-body">
                            <form action="{{ route('permission.update', $permission->id) }}" method="POST">
                                @csrf
                                @method('PATCH')
                                <div class="row">
                                    <div class="col">
                                        <input type="text" class="form-control" name="name" id="name"
                                            value="{{ $permission->name }}" autofocus>
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="btn btn-success">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
@stop

resources/views/admin/permission/index.blade.php
@extends('layouts.app')

@section('title', 'Permissions')

@section('content')

    @if (session()->has('pesan'))
        <div class="alert alert-success alert-dismissible show fade">
            <div class="alert-body">
                <button class="close" data-dismiss="alert">
                    <span>×</span>
                </button>
                {{ session()->get('pesan') }}
            </div>
        </div>
    @endif

    <section class="section">
        <div class="section-header">
            <h1>Management users - permission</h1>
        </div>

        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            {{-- <h4>Advanced Table</h4> --}}
                            <a href="{{ route('permission.create') }}" class="btn btn-icon icon-left btn-primary"><i
                                    class="fas fa-plus"></i> Create</a>
                            {{-- <div class="card-header-form">
                            <form>
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-btn">
                                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div> --}}
                        </div>
                        <div class="card-body p-0">
                            {{-- <div class="table-responsive"> --}}
                            <table class="table table-hover table-md     ml-4">
                                <tr>
                                    {{-- <th width="5%">
                                            <div class="custom-checkbox custom-control">
                                                <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad"
                                                    class="custom-control-input" id="checkbox-all">
                                                <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                                            </div>
                                        </th> --}}
                                    <th width="5%">No</th>
                                    <th>Nama</th>
                                    <th>Aksi</th>
                                </tr>

                                @php
                                    $no = 1;
                                @endphp
                                @foreach ($permissions as $permission)
                                    <tr>
                                        {{-- <td></td> --}}
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $permission->name }}</td>
                                        <td>
                                            <a href="{{ route('permission.edit', $permission->id) }}"
                                                class="btn btn-warning btn-sm"><i class="fas fa-edit"></i></a>
                                            <form action="{{ route('permission.destroy', $permission->id) }}" method="POST"
                                                style="display: contents">
                                                @csrf
                                                @method('DELETE')

                                                <button type="submit" class="btn btn-danger btn-sm"
                                                    onclick="return hapus()"><i class="fas fa-trash"></i></button>
                                            </form>

                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                            {{-- </div> --}}
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>

@stop

@push('js')

    <script>
        function hapus() {
            if (confirm('Are you sure you want to delete this data? Data that has been deleted cannot be recovered !!!')) {
                return true;
            } else {
                return false;
            }
        }
    </script>
@endpush