routes/web.php
<?php

use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\RoleSetupController;
use App\Http\Controllers\Admin\SurveyController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\UserSetupController;
use GuzzleHttp\Middleware;
use Illuminate\Http\Request;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::middleware(['auth'])->group(function () {
    Route::get('home', function () {
        return view('dashboard.home');
    })->name('home');

    Route::prefix('admin')->group(function () {
        Route::resource('user', UserController::class);
        Route::get('user/setup/{id}', [UserSetupController::class, 'index'])->name('user.setup');
        Route::post('user/setup', [UserSetupController::class, 'store'])->name('user.setup.store');
        Route::resource('permission', PermissionController::class);
        Route::resource('role', RoleController::class)->except(['show']);
        Route::get('role/setup/{id}', [RoleSetupController::class, 'index'])->name('role.setup');
        Route::post('role/setup', [RoleSetupController::class, 'store'])->name('role.setup.store');
        Route::resource('department', DepartmentController::class);
        Route::get('user/setup/department/{id}', [UserSetupController::class, 'indexDepartment'])->name('user.setup.department');
        Route::post('user/setup/department', [UserSetupController::class, 'storeDepartment'])->name('user.setup.department.store');
    });
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'bio',
        'phone',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function userDepartment()
    {
        return $this->hasMany(UserDepartment::class, 'user_id', 'id')->with('department');
    }
}

app/Models/Users.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Users extends Model
{
    use HasFactory;

    protected $table = 'users';

    public function hasDepartment()
    {
        return $this->hasOne(UserDepartment::class, 'user_id', 'id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    public function index()
    {
        // dd(auth()->user()->roles);
        // $users = User::with('unit')->orderBy('name')->get();
        $users = User::orderBy('name')->get();
        return view('admin.user.index', compact('users'));
    }

    public function create()
    {
        // $unit = Unit::all();
        return view('admin.user.create');
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
            'username' => 'required',
            'password' => 'required',
            // 'unit_id' => 'required',
        ]);

        DB::table('users')->insert([
            'name' => $request->name,
            'username' => $request->username,
            'password' => bcrypt($request->password),
            // 'unit_id' => $request->unit_id,
        ]);

        return redirect('admin/user')->with('pesan', 'Data has been saved !');
    }

    public function edit($id)
    {
        $user = User::find($id);
        // $unit = Unit::all();

        return view('admin.user.edit', compact('user'));
    }

    public function update($id, Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
            'username' => 'required',
            // 'unit_id' => 'required',
        ]);

        if ($request->password != null) {
            $password = bcrypt($request->password);
        } else {
            $password = User::find($id)->password;
        }

        User::whereId($id)->update([
            'name' => $request->name,
            'username' => $request->username,
            'password' => $password,
            // 'unit_id' => $request->unit_id,
        ]);

        return redirect('admin/user')->with('pesan', 'Data has been changed !');
    }

    public function destroy($id)
    {
        User::whereId($id)->delete();

        return redirect('admin/user')->with('pesan', 'Data has been deleted !');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah User')

@section('content_header')
    <h1>User</h1>
@stop

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>User - Create user</h1>
        </div>

        <div class="section-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route('user.store') }}" method="POST">
                                {{ csrf_field() }}
                                <div class="row">
                                    <div class="col">
                                        <label for="name">Name</label>
                                        <input type="text" class="form-control" name="name" id="name" autofocus>
                                    </div>
                                    <div class="col">
                                        <label for="name">Username</label>
                                        <input type="text" class="form-control" name="username" id="username" autofocus>
                                    </div>
                                    <div class="col">
                                        <label for="name">Password</label>
                                        <input type="password" class="form-control" name="password" id="password"
                                            autofocus>
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="btn btn-success mt-4">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
@stop

@section('css')

@stop

@section('js')

@stop

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit User')

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>User - Edit user</h1>
        </div>

        <div class="section-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route('user.update', $user->id) }}" method="POST">
                                @csrf
                                @method('PATCH')
                                <div class="row">
                                    <div class="col">
                                        <label for="name">Name</label>
                                        <input type="text" class="form-control" name="name" id="name"
                                            value="{{ $user->name }}" autofocus>
                                    </div>
                                    <div class="col">
                                        <label for="name">Username</label>
                                        <input type="text" class="form-control" name="username" id="username"
                                            value="{{ $user->username }}">
                                    </div>
                                    <div class="col">
                                        <label for="name">Password</label>
                                        <input type="password" class="form-control" name="password" id="password">
                                    </div>
                                    <div class="col">
                                        <button type="submit" class="btn btn-success mt-4">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
@stop

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('title', 'User')

@section('content')

    @if (session()->has('pesan'))
        <div class="alert alert-success alert-dismissible show fade">
            <div class="alert-body">
                <button class="close" data-dismiss="alert">
                    <span>×</span>
                </button>
                {{ session()->get('pesan') }}
            </div>
        </div>
    @endif

    <section class="section">
        <div class="section-header">
            <h1>Management users - user</h1>
        </div>

        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{ route('user.create') }}" class="btn btn-icon icon-left btn-primary"><i
                                    class="fas fa-plus"></i> Create</a>
                        </div>
                        <div class="card-body p-0">
                            <table class="table table-hover table-md ml-4">
                                <tr>
                                    <th width="5%">No</th>
                                    <th>Nama</th>
                                    <th>Username</th>
                                    <th>Role</th>
                                    <th>Department</th>
                                    <th>Aksi</th>
                                </tr>

                                @php
                                    $no = 1;
                                @endphp
                                @foreach ($users as $user)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->username }}</td>
                                        <td>
                                            @if ($user->roles)
                                                @foreach ($user->roles as $role)
                                                    {{ $role->name }} <br>
                                                @endforeach
                                            @endif
                                        </td>
                                        <td>
                                            @forelse ($user->userDepartment as $userDepartmentItem)
                                                {{ $userDepartmentItem->department->name }} <br>
                                            @empty
                                            @endforelse
                                        </td>
                                        <td>
                                            <a href="{{ route('user.edit', $user->id) }}" class="btn btn-warning btn-sm"><i
                                                    class="fas fa-edit" data-toggle="tooltip" data-placement="top" title="Edit user"></i></a>
                                            <form action="{{ route('user.destroy', $user->id) }}" method="POST"
                                                style="display: contents">
                                                @csrf
                                                @method('DELETE')

                                                <button type="submit" class="btn btn-danger btn-sm"
                                                    onclick="return hapus()"><i class="fas fa-trash" data-toggle="tooltip" data-placement="top" title="Delete user"></i></button>
                                            </form>
                                            <a href="{{ route('user.setup', $user->id) }}" class="btn btn-primary btn-sm"
                                                data-toggle="tooltip" data-placement="top" title="Setup user"><i
                                                    class="fas fa-user-cog"></i></a>
                                            <a href="{{ route('user.setup.department', $user->id) }}" class="btn btn-primary btn-sm"
                                                data-toggle="tooltip" data-placement="top" title="Setup user department"><i
                                                    class="fas fa-building"></i></a>

                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>

@stop

@section('css')

@stop

@section('js')

    <script>
        function hapus() {
            if (confirm('Apa anda yakin akan menghapus data ini? Data yang sudah dihapus tidak dpaat dikembalikan !!!')) {
                return true;
            } else {
                return false;
            }
        }
    </script>
@stop

resources/views/admin/user/setup-department.blade.php
@extends('layouts.app')

@section('title', 'Setup user department')

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>Setup user department</h1>
        </div>

        <div class="section-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route('user.setup.department.store') }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="user_id" value="{{ $user->id }}">
                                @foreach ($departments as $department)
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="department[{{ $department->id }}]"
                                            value="{{ $department->name }}" @isset ($userDepartment[$department->id]) checked @endisset>
                                        <label class="form-check-label">
                                            {{ $department->name }}
                                        </label>
                                    </div>
                                @endforeach
                                <br>
                                <button class="btn btn-success" type="submit">Save</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
@stop

resources/views/admin/user/setup.blade.php
@extends('layouts.app')

@section('title', 'Setup role user')

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>Role - Setup role user</h1>
        </div>

        <div class="section-body">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route('user.setup.store') }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="id" value="{{ $user->id }}">
                                @foreach ($roles as $role)
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="role[]"
                                            value="{{ $role->name }}" @if ($user->hasRole($role->name)) checked @endif>
                                        <label class="form-check-label">
                                            {{ $role->name }}
                                        </label>
                                    </div>
                                @endforeach
                                <br>
                                <button class="btn btn-success" type="submit">Save</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
@stop